In [4]:
 #Import necessary libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
#Import dataset (exam_dataset.csv)

ds_b=pd.read_csv('exam_dataset.csv')
ds_b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Age                      1470 non-null   int64 
 1   BusinessTravel           1470 non-null   object
 2   MonthlyIncome            1470 non-null   int64 
 3   JobSatisfaction          1470 non-null   int64 
 4   Bonus                    1470 non-null   int64 
 5   Department               1470 non-null   object
 6   DistanceFromHome         1470 non-null   int64 
 7   Education                1470 non-null   int64 
 8   EducationField           1470 non-null   object
 9   EmployeeCount            1470 non-null   int64 
 10  EmployeeNumber           1470 non-null   int64 
 11  EnvironmentSatisfaction  1470 non-null   int64 
 12  Gender                   1470 non-null   object
 13  JobLevel                 1470 non-null   int64 
 14  JobRole                  1470 non-null  

In [6]:
#  Allocate the relevant attributes as input and output
     #Input  : [0]Age, [1]BusinessTravel, [2]MonthlyIncome, [3]JobSatisfaction
     #Output : [23] Attrition

x=ds_b.iloc[:,[0,1,2,3]].values
y=ds_b.iloc[:,23].values

In [7]:
#check x

x

array([[41, 'Travel_Rarely', 5993, 4],
       [49, 'Travel_Frequently', 5130, 2],
       [37, 'Travel_Rarely', 2090, 3],
       ...,
       [27, 'Travel_Rarely', 6142, 2],
       [49, 'Travel_Frequently', 5390, 2],
       [34, 'Travel_Rarely', 4404, 3]], dtype=object)

In [8]:
#check y

y

array(['Yes', 'No', 'Yes', ..., 'No', 'No', 'No'], dtype=object)

In [9]:
# LabelEncoder to encode categorical data

from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
x[:, 1]= labelencoder_X.fit_transform(x[:, 1])

labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)  # [1] Yes, [0] No

In [10]:
#check new x after transform to all integers values

x

array([[41, 2, 5993, 4],
       [49, 1, 5130, 2],
       [37, 2, 2090, 3],
       ...,
       [27, 2, 6142, 2],
       [49, 1, 5390, 2],
       [34, 2, 4404, 3]], dtype=object)

In [11]:
#check new y after transform to all integers values

y

array([1, 0, 1, ..., 0, 0, 0])

In [12]:
# Split data into training and test sets with the appropriate proportions (75% training set:25% test set)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [13]:
# Normalized data using StandardScaler

from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)

In [14]:
# Fit the and predict results using the Classifier (Random Forest)

from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=50,criterion='entropy',random_state=0)
classifier.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=50, random_state=0)

In [15]:
y_pred=classifier.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [16]:
x_test

array([[-0.09124542, -2.38889579,  0.74143923,  1.15677915],
       [-0.42383347,  0.59248944, -0.45760097, -0.66953979],
       [-0.20210811, -0.89820317, -0.39531867,  0.24361968],
       ...,
       [ 0.463068  ,  0.59248944, -0.3726513 , -1.58269926],
       [ 1.23910679,  0.59248944,  0.30037886,  1.15677915],
       [-0.64555884, -0.89820317, -0.18283858,  1.15677915]])

In [17]:
# Evaluate results using confusion matrix and calculate the prediction accuracy

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[294,  16],
       [ 50,   8]], dtype=int64)

In [18]:
from sklearn.metrics import accuracy_score
AR=accuracy_score(y_test,y_pred)
print('Prediction Accuracy:', AR)

Prediction Accuracy: 0.8206521739130435


In [19]:
# Discuss the results and findings

#Answer: #Random Forest classification technique is used for the prediction of this categorical data. 
         #The independent variables are ‘Age’, ‘BusinessTravel’, ‘MonthlyIncome’ and ‘JobSatisfaction'.
         #While the dependent variable is 'Attrition'.
         #The dataset is splitted to 75% training set and 25% testing set.
         #By calculating the prediction accuracy usng the confusion matrix, the value is 0.82 or 82% accurate.
         #Since, the high value of prediction accuracy, we can safely use this model.